### ISSUE TITLE
Update to latest Mapbox.js

### ISSUE THREAD

**Issue by ughitsaaron** [jlord/sheetsee-maps#10]
Seems like the Mapbox.js version is out of date. I'd be happy to do some work on this later this weekend/next week?

**Comment by oeon** [comment]
I noticed this recently too. One can only use v3 map.id's - _if_ you have some old ones in your Mapbox account, https://www.mapbox.com/help/blank-tiles/#youre-using-v3-of-the-maps-api. What is involved in this type of work?

**Comment by potagit** [comment]
@ughitsaaron I noticed the same behavior. For your information I'm on eon, so that could come from the dist-upgrade repo for some reason?

@jlord I had the Leaftlet on my side too, but I was wondering if I could link a login request coming from top dependencies comin from another website using ssl cerification verification or pgp key signature verification. This is all to be link to my personnal website which I've been trying to have access to.

Maybe add @oeon Joe Larson to the pull request? I'm opened to suggestion.

I'm on Ubuntu Eoan 19.10 
#Maybe something to do with next upgrade in April?
